#!/usr/bin/env bash

set -euo pipefail

function abspath() {
  readlink -m "$1"
}

export THIS_DIR=$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd
)

SUCCESS="({ set +x; } 2> /dev/null && echo '🟩 Success' && exit 0)"
FAILURE="({ set +x; } 2> /dev/null && echo '🟥 Failure' && exit 1)"
CANCELLED="({ set +x; } 2> /dev/null && echo '🟦 Cancelled' && exit 0)"
SUCCESS_OR_FAILURE="&& ${SUCCESS} || ${FAILURE}"
HANDLE_SIGINT="trap \"${CANCELLED}; exit 0\" INT"

export PACKAGE_DIR_REL=""
export PROJECT_ROOT_DIR="$(abspath "${THIS_DIR}")"
export PACKAGE_DIR="$(abspath "${PROJECT_ROOT_DIR}/${PACKAGE_DIR_REL}")"

export DOCKER_REPO="neherlab/pangraph.jl"
export DOCKER_IMAGE_NAME_SAFE="${DOCKER_REPO//\//-}"
export DOCKER_CONTAINER_NAME="${DOCKER_IMAGE_NAME_SAFE}-$(date -u "+%Y-%m-%d_%H-%M-%S_%3NZ")"

export USER=user
export GROUP=user

export BUILD_DIR_REL=".build/docker/${PACKAGE_DIR_REL}"
export BUILD_DIR="$(abspath "${PACKAGE_DIR}/${BUILD_DIR_REL}")"
export BUILD_DIR_TEST="${BUILD_DIR}/test"

export CACHE_DIR_REL=".cache/docker/${PACKAGE_DIR_REL}"
export CACHE_DIR="$(abspath "${PACKAGE_DIR}/${CACHE_DIR_REL}")"

export NICE="nice -14 ionice -c2 -n3"
export TIME="/usr/bin/time -f \"Cmd : %C\nTime: %E\nMem : %M KB\n\""

if [ -f "${PROJECT_ROOT_DIR}/.env.example" ]; then
. "${PROJECT_ROOT_DIR}/.env.example"
fi
if [ -f "${PROJECT_ROOT_DIR}/.env" ]; then
  . "${PROJECT_ROOT_DIR}/.env"
fi

JUPYTER=0

case "${1:-}" in
"jupyter" | "j")
  shift
  JUPYTER=1
  ;;
esac

DOCKER_BASE_IMAGE="${DOCKER_BASE_IMAGE:=ubuntu:22.04}"
DOCKER_TARGET="dev"

DOCKER_IMAGE_VERSION="$(find \
  .dockerignore \
  .gitignore \
  docker-dev \
  docker/**/* \
  Manifest.toml \
-type f -print0 | sort -z | xargs -0 cat | sha256sum| cut -f 1 -d ' ')"

if ! docker inspect --format '{{.Id}}' "${DOCKER_REPO}:${DOCKER_TARGET}-${DOCKER_IMAGE_VERSION}" &>/dev/null; then

  export DOCKER_BUILDKIT=1
  export BUILDKIT_PROGRESS=plain
  export PROGRESS_NO_TRUNC=1

  if ! docker buildx inspect "${DOCKER_IMAGE_NAME_SAFE}" &>/dev/null; then
    docker buildx create --use --name "${DOCKER_IMAGE_NAME_SAFE}" --driver docker-container --driver-opt network=host >/dev/null
  fi

  BRANCH="$(git rev-parse --abbrev-ref HEAD || echo "${GITHUB_REF_NAME:=}")"
  CACHE_SCOPE="${DOCKER_REPO}-${DOCKER_TARGET}-${BRANCH}"
  BUILDX_CACHE_DIR="${CACHE_DIR}/buildx"

  ${NICE} docker buildx build \
    --builder=${DOCKER_IMAGE_NAME_SAFE} \
    --load \
    --file="docker/docker-dev.dockerfile" \
    --target="${DOCKER_TARGET}" \
    --tag="${DOCKER_REPO}" \
    --tag="${DOCKER_REPO}:${DOCKER_TARGET}" \
    --tag="${DOCKER_REPO}:${DOCKER_TARGET}-${DOCKER_IMAGE_VERSION}" \
    --cache-from="${DOCKER_REPO}" \
    --cache-from="${DOCKER_REPO}:dev" \
    --cache-from="${DOCKER_REPO}:${DOCKER_TARGET}" \
    --cache-from="${DOCKER_REPO}:${DOCKER_TARGET}-${DOCKER_IMAGE_VERSION}" \
    --cache-from="type=local,src=${BUILDX_CACHE_DIR},scope=${CACHE_SCOPE}" \
    --cache-to="type=local,dest=${BUILDX_CACHE_DIR},mode=max,compression=zstd,scope=${CACHE_SCOPE}" \
    --network=host \
    --build-arg="DOCKER_BASE_IMAGE=${DOCKER_BASE_IMAGE}" \
    --build-arg="UID=$(id -u)" \
    --build-arg="GID=$(id -g)" \
    --build-arg="USER=user" \
    --build-arg="GROUP=user" \
    . \
    >/dev/null

fi

PARAMS=""
COMMAND=${*:-bash}
PORTS=
if [ "${JUPYTER}" == "1" ]; then
  COMMAND="/files/start-jupyter"
elif [ -z "${*:-}" ]; then
  COMMAND="bash"
else
  COMMAND="$(printf " %q" "${@}")"
fi

mkdir -p \
  "${BUILD_DIR}" \
  "${CACHE_DIR}" \
  "${CACHE_DIR}/.julia" \
  "${CACHE_DIR}/.jupyter"

ADDITIONAL_DOCKER_RUN_ARGS=""
if [ -t 1 ]; then
  ADDITIONAL_DOCKER_RUN_ARGS="${ADDITIONAL_DOCKER_RUN_ARGS} -it"
fi

# shellcheck disable=SC2086
${NICE} docker run --rm \
  ${ADDITIONAL_DOCKER_RUN_ARGS} \
  --init \
  --name="${DOCKER_CONTAINER_NAME}" \
  --hostname="${DOCKER_IMAGE_NAME_SAFE}" \
  --user="$(id -u):$(id -g)" \
  --volume="${PROJECT_ROOT_DIR}:/workdir" \
  --volume="${CACHE_DIR}/.julia:/home/${USER}/.julia" \
  --volume="${CACHE_DIR}/.jupyter:/home/${USER}/.jupyter" \
  --workdir="/workdir/${PACKAGE_DIR_REL}" \
  --env="UID=$(id -u)" \
  --env="GID=$(id -g)" \
  --env="USER=${USER}" \
  --env="GROUP=${GROUP}" \
  --env="PS1=\${USER}@\${HOST}" \
  -p "10000:8888" \
  --ulimit core=0 \
  ${PORTS} \
  "${DOCKER_REPO}" \
  ${NICE} bash -c "set -euo pipefail; ${HANDLE_SIGINT}; ${NICE} ${TIME} ${COMMAND} ${SUCCESS_OR_FAILURE}"
