[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pypangraph"
version = "1.0.1"
authors = [
  { name="Marco Molari", email="mmolari91@gmail.com" },
]
description = "package to manipulate pangenomes produced by PanGraph"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "matplotlib",
  "numpy",
  "pandas",
  "biopython",
  "jsonschema",
]

[tool.setuptools.package-data]
"Pangraph.schema.json" = ["Pangraph.schema.json"]

[project.urls]
Homepage = "https://docs.pangraph.org"
Documentation = "https://docs.pangraph.org"
Repository = "https://github.com/neherlab/pangraph"
Issues = "https://github.com/neherlab/pangraph/issues"
