[package]
name = "minimap2"

authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
eyre = { workspace = true }
itertools = { workspace = true }
minimap2-sys = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]

[features]
serde = ["dep:serde"]
