#!/usr/bin/env bash

# Runs bulk cross-compilation of CLI binaries for all supported platforms
# each in a separate tmux window
#
# Kill tmux server with `Ctrl`+`b` followed by `k` (change `b` to your "prefix" shortcut if it's not default)

set -euo pipefail

targets=(
  "aarch64-apple-darwin"
  "aarch64-unknown-linux-gnu"
  "aarch64-unknown-linux-musl"
  "x86_64-apple-darwin"
  "x86_64-pc-windows-gnu"
  "x86_64-unknown-linux-gnu"
  "x86_64-unknown-linux-musl"
)

tmux new-session -d -s build
tmux send-keys -t build 'exit' C-m  # Close the initial shell to start with a clean layout

# begin: eye candy options
tmux set -g mouse on
tmux set -g default-terminal "screen-256color"
tmux unbind k
tmux bind k kill-session
tmux set -g pane-border-status top
tmux set -g pane-border-format "#{pane_title}"
tmux set -g pane-border-style "bg=colour235,fg=colour8"
tmux set -g pane-active-border-style "bg=colour242,fg=colour237"
# end: eye candy options

for target in "${targets[@]}"; do
  tmux split-window -v -t build "CROSS=${target} ./docker/dev br; echo 'Build finished for ${target}'; exec $SHELL"
  tmux select-layout -t build even-vertical
  tmux select-pane -t "" -T "${target}"
done
tmux kill-pane -t 0  # Remove the initial empty pane
tmux attach -t build
