[package]
name = "pangraph-cli"

authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

build = "src/build.rs"

[lints]
workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
color-eyre = { workspace = true }
ctor = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
pangraph = { path = "../pangraph" }
rayon = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }

[build-dependencies]
eyre = { workspace = true }
pangraph = { path = "../pangraph" }
schemars = { workspace = true }
