#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/env

raw=$seqdir/singles
aln=$alndir/singles

if [ ! -d $raw ]; then
    echo "Fasta directory not found"
elif [ ! -d $aln ]; then
    echo "Alignment directory not found"
else
    python $pydir/make_distmatrix.py $raw $aln
fi
