#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/env

mtx=$root/data/$1.npz

if [ ! -f $mtx ]; then
    echo "Distance matrix not found"
else
    python $pydir/graph_matrix.py $mtx
fi
