#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/env

raw=$seqdir/$1*.fasta
dir=$seqdir/singles

if [ ! -f $raw ]; then
    echo "Fasta not found"
elif [ ! -d $dir ]; then
    echo "Directory not made"
else
    python $pydir/split_fasta.py $raw $dir
fi
