#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/env

raw=$seqdir/$1*.fa*
out=$alndir/$1.paf

if [ ! -f $raw ]; then
    echo "Fasta not found"
else
    minimap2 -x asm5 -D -c  $raw $raw > $out
fi
