#!/bin/python

import os

from glob import glob

# ------------------------------------------------------------------------
# Global constants

ROOT = "data/graph/aln"

# ------------------------------------------------------------------------
# Global Functions

def selfmap(graph, out):
    print("----> Starting map")
    os.system(f"minimap2 -ax asm5 {graph} {graph} 1> {out}.sam 2>log")
    print("----> Done w/ map")

# ------------------------------------------------------------------------
# Main point of entry
if __name__ == "__main__":
    for gpath in glob(f"{ROOT}/*.fa"):
        print(f"--> Analyzing {gpath}")
        base = os.path.basename(gpath).split(".")[0]
        selfmap(gpath, f"{ROOT}/{base}")
