#!/bin/bash -e

if [[ $# -lt 4 ]]; then
    echo 'please provide a path to the script and a path store the resulting JLD2 file'
    exit 1
fi

asm="$1"; shift 1

seq="$1"
cmd="$2"
out="$3"
data="data/synthetic"
pipe="$data/pipe"

trap 'cleanup' ERR

initpipe()
{
    if [[ -e $pipe ]]; then
        closepipe
    fi
    mkfifo "$pipe"
}

closepipe()
{
    exec 3>&-
    rm -f "$pipe"
}

cleanup()
{
    closepipe
    rm -f "$out"
}

blockif()
{
    while [[ $(jobs -pr | wc -l) -gt "$1" ]]
    do
        sleep 5
    done
}

export JULIA_NUM_THREADS=1 # ensure we don't run mulithreaded

# simulation parameters
N=100; T=50; L=50000

hgts="1e-2 5e-2 1e-1 5e-1 1"
# snps="1e-4 2.5e-4 5e-4 7.5e-4 1e-3 2.5e-3 5e-3 7.5e-3 1e-2" # broad
# snps="1e-3 2e-3 3e-3 4e-3 5e-3 6e-3 7e-3 8e-3 9e-3 1e-2" #extends too far
snps="5e-4 6e-4 7e-4 8e-4 9e-4 1e-3 2e-3 3e-3 4e-3 5e-3"

# open up the consumer process
initpipe
{ julia --project=script "$cmd" "$pipe" "$out"; }&
pid=$!
exec 3>"$pipe"

# main simulation loop
for hgt in $hgts
do
    for snp in $snps
    do
        for nit in {1..25}
        do
            blockif 9 # ensure we don't throttle the system
            (
                known=$(mktemp /tmp/known.json.XXXXXX)
                guess=$(mktemp /tmp/guess.json.XXXXXX)

                if [[ "$asm" == "mmseqs" ]]; then
                    julia --project=script "$seq" -N "$N" -L "$L" \
                  | pangraph generate -m "$snp" -r "$hgt" -t "$T" -i "1e-2" -o "$known" \
                  | pangraph build --circular -a 0 -b 0 --alignment-kernel mmseqs \
                    1>"$guess" 2>/dev/null
                else
                    julia --project=script "$seq" -N "$N" -L "$L" \
                  | pangraph generate -m "$snp" -r "$hgt" -t "$T" -i "1e-2" -o "$known" \
                  | pangraph build --circular -a 0 -b 0 -s "$asm" \
                    1>"$guess" 2>/dev/null
                fi
                # NOTE: concurrent writes to a pipe are guaranteed to be atomic,
                # provided they are smaller than the buffer. This, in turn, is
                # at minimum 512 bytes. We are fine without explicit locking...
                printf "%.1e;%.1e;%02d;%s;%s\n" "$hgt" "$snp" "$nit" "$known" "$guess" 1>&3

                # NOTE: dont remove here for data race reason.
                # instead, do so in the write kernel
                # rm $known $guess
            )&
        done
    done
done

# find extant pids (that are not consumer), wait for them
mapfile -t children < <(jobs -p | grep -v "$pid")
for child in "${children[@]}"
do
    wait "$child"
done
# done, now close our pipe
closepipe
# wait for our consumer to cleanup
wait "$pid"
# verify cleanup
rm -f /tmp/{guess,known}.json.??????
