#!/bin/bash -e

self="${0}"
input=$1;  shift 1
output=$1; shift 1
args=( "$@" )

fasta=("${args[@]::$((${#args[@]} / 2))}")
genbk=("${args[@]:$((${#args[@]} / 2))}")

{
    for i in "${!fasta[@]}"
    do
        cat "${fasta[i]}"
        echo "ENDSEQ"
        script/extract-gene "${genbk[i]}"
        echo "ENDGENE"
    done
} | julia --project=script "$self.jl" "$input" 1>"$output"
