from snakemake.utils import min_version
min_version("6.0")

module accuracy_mod:
    snakefile: "rules/accuracy.smk"
    config: config

module panx_benchmark_mod:
    snakefile: "rules/panx.smk"
    config: config

use rule * from accuracy_mod as acm_*

use rule * from panx_benchmark_mod as pxm_*

rule clean:
    shell:
        """
        rm log/*
        """