#!/usr/bin/env bash
#
# Re-generates CLI reference in Markdown format
#
# Usage:
#   ./scripts/update_cli_reference_docs <path_to_executable>

set -euo pipefail
trap "exit" INT

# Directory where this script resides
THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"

EXE="${1:-exe}"
OUTPUT="${THIS_DIR}/../docs/docs/usage/reference.md"

# Add header
cat << EOF > "${OUTPUT}"
---
sidebar_position: 9999
---
EOF

# Append body
./"${EXE}" help-markdown >> "${OUTPUT}"
