[package]
name = "pangraph"
description = "A bioinformatic toolkit to align genome assemblies into pangenome graphs"
version = "1.0.0"
documentation = "https://neherlab.github.io/pangraph"
homepage = "https://neherlab.github.io/pangraph"
repository = "https://github.com/neherlab/pangraph"
edition = "2021"
license = "MIT"
publish = false
keywords = [
  "bacteria",
  "bioinformatics",
  "genome",
  "pangenome",
  "pangraph"
]

[lib]
crate-type = ["lib"]

[dependencies]
approx = "=0.5.1"
argmin = { version = "=0.8.1", features = [] }
chrono = { version = "=0.4.21", default-features = false, features = ["clock", "std"] }
clap = { version = "=3.2.16", features = ["derive"] }
clap_complete = "=3.2.3"
clap_complete_fig = "=3.2.4"
color-eyre = "=0.6.2"
csv = "=1.2.2"
ctor = "=0.1.23"
env_logger = "=0.9.0"
eyre = "=0.6.8"
flate2 = "=1.0.28"
itertools = "=0.10.3"
lazy_static = "=1.4.0"
log = "=0.4.17"
minimap2 = "=0.1.16"
ndarray = { version = "=0.15.6", features = ["rayon", "serde", "approx-0_5", "blas"] }
ndarray-rand = "=0.14.0"
ndarray-stats = "=0.5.1"
noodles = { version = "=0.30.0", features = ["core", "bam", "sam"] }
num = "=0.4.0"
num-integer = "=0.1.45"
num-traits = "=0.2.15"
num_cpus = "=1.13.1"
openblas-src = { version = "=0.10.8", features = ["static"] }
parking_lot = { version = "=0.12.1", features = ["deadlock_detection", "hardware-lock-elision", "serde", "arc_lock"] }
pretty_dtoa = "=0.3.0"
rand = { version = "=0.8.5", features = ["serde1", "log"] }
rand_distr = { version = "=0.4.3", feaures = ["serde1", "std_math"] }
rand_isaac = { version = "=0.3.0", features = ["serde1"] }
rayon = "=1.5.3"
serde = { version = "=1.0.143", features = ["derive"] }
serde-aux = "=4.2.0"
serde_json = { version = "=1.0.83", features = ["preserve_order", "unbounded_depth"] }
serde_stacker = { version = "=0.1.6" }
smart-default = "=0.6.0"
strum = "=0.24.1"
strum_macros = "=0.24.3"
tempfile = "=3.8.1"

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
mimalloc = { version = "=0.1.29", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
atty = "=0.2.14"
bzip2 = "=0.4.4"
xz2 = "=0.1.7"
zstd = { version = "=0.11.2", features = ["zstdmt"] }

[dev-dependencies]
pretty_assertions = "=1.2.1"
rstest = "=0.15.0"
rstest_reuse = "=0.4.0"
