on:
  push:
    branches: [ 'master', 'release-docs' ]

  pull_request:
    paths:
      - 'docs/**'

concurrency:
  group: docs-${{ github.workflow }}-${{ github.ref_type }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  GITHUB_REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}

jobs:

  docs:
    name: "docs"
    runs-on: "ubuntu-24.04"
    environment:
      name: ${{ github.ref }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
          lfs: true

      - uses: "actions/setup-node@v4"
        with:
          node-version: "22"

      - name: "Install deps"
        run: |
          sudo apt-get install rename --yes -qq >/dev/null

          cd docs/
          npm install -g bun
          bun install

      - name: "Build docs"
        run: |
          cd docs/
          bun prod:build

      - name: "Deploy docs"
        if: endsWith(github.ref, '/release-docs')
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd docs/
          ./deploy

      - name: "Create git tag"
        if: endsWith(github.ref, '/release-docs')
        run: |
          git config --global user.name "${{ secrets.NEHERLAB_BOT_GITHUB_NAME }}"
          git config --global user.email "${{ secrets.NEHERLAB_BOT_GITHUB_EMAIL }}"

          version=$(date --utc +%Y-%m-%d_%H-%M-%SZ)

          git tag "docs-${version}"
          git push origin "docs-${version}"
